Azure OpenAI encoder
pinecone-io/pinecone-text pull request #56
Opened 2023-11-27 10:22 UTC by MichaelAnckaert

## Problem

Azure OpenAI can't be used with this library. I stumbled upon this issue when I tried to implement the Azure OpenAI client for use with the *canopy-sdk*. 

## Solution

This PR implements the dense encoder using the Azure OpenAI embeddings. I subclassed a new encoder from the existing `OpenAIEncoder` and used the `AzureOpenAI` client. 

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

No specific tests were added as the existing `OpenAIEncoder` tests should cover all use cases.

2023-12-03 12:34 UTC, acatav requested changes
Thanks @MichaelAnckaert for your contribution. Can you please add tests? we'll make sure all required env vars will be available in CI via github secrets

2023-12-03 12:34 UTC, acatav commented on pinecone_text/dense/openai_encoder.py
> +class AzureOpenAIEncoder(OpenAIEncoder):
Can you please add system and unit tests same as we have for OpenAI non Azure embeddings?

2024-01-10 15:23 UTC, acatav commented
@MichaelAnckaert Thanks for you contribution! we wanted to merge this PR ASAP so we added tests and changed the code to align with this project high level design.

2024-01-11 11:00 UTC, igiloh-pinecone approved these changes
LGTM!

2024-01-11 11:05 UTC, merged