add JinaEncoder class to handle Jina Embeddings
pinecone-io/pinecone-text pull request #59
Opened 2023-12-05 09:56 UTC by JoanFM

Adding JinaEncoder class to allow users to use Jina Embeddings using Jina Embedding API https://jina.ai/embeddings/

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Infrastructure change (CI configs, etc)
- [ ] Non-code change (docs, etc)
- [ ] None of the above: (explain here)

## Test Plan

Unit tests have been added

2023-12-05 10:09 UTC, JoanFM commented
Adding unit tests to class

2023-12-05 10:46 UTC, JoanFM commented
> Adding unit tests to class

Done

2023-12-07 21:38 UTC, igiloh-pinecone requested changes
@JoanFM thank you very much for your contribution!

Please see only one comment about missing a system (==integration) test. Other than that LGTM

2023-12-11 10:11 UTC, JoanFM commented on tests/unit/test_jina_encoder.py
Hey @igiloh-pinecone ,

System test added as request. Please check

2024-01-11 14:45 UTC, igiloh-pinecone approved these changes
LGTM!

2024-01-14 17:05 UTC, merged